#!/usr/bin/env bash
#  ▄▄▄· ▄▄▄  ▄▄▄▄▄▪  ▐▄• ▄
# ▐█ ▀█ ▀▄ █·•██  ██  █▌█▌▪
# ▄█▀▀█ ▐▀▀▄  ▐█.▪▐█· ·██·
# ▐█ ▪▐▌▐█•█▌ ▐█▌·▐█▌▪▐█·█▌
#  ▀  ▀ .▀  ▀ ▀▀▀ ▀▀▀•▀▀ ▀▀
#---- 1.System
# Grub
alias grupdate="sudo grub-mkconfig -o /boot/grub/grub.cfg"

#---- 2.Package manager
#---2.1 SEARCH
# Search in online repositories
alias pacss="yay -Ss"
# Search local packages
alias pacssl="yay -Qs"
# Search for package info
alias pacinf="yay -Qi"
# Search for package files
alias pacfiles="yay -Ql"

#---2.2 INSTALL
# Istall from remote repository
alias pacin="yay -S"
# Install from local package
alias pacinl="yay -U"
# Download a package
alias pacdw="yay -Sw"

#---2.3 REMOVE
# Remove a package
alias pacrm="yay -R"
# Remove completly include dependencies
alias pacrmf="yay -Rns"
# Remove unneeded dependecy
alias pacnd="yay -Rns $(yay -Qtdq)"
# Remove old downloaded packages
alias paccl="yay -Scc"

#---2.4 UPDATE
# Update repositories database
alias pacu="yay -Sy"
# Upgrade packages
alias pacug="yay -Su"
# List avaible upgrades
alias paculs="yay -Qu"

#---2.5 OTHERS
alias addgpg="gpg --keyserver pool.sks-keyservers.net --recv-keys"
alias pacunlock="sudo rm /var/lib/pacman/db.lck"

#---- 3.Configuration files | dotfiles
#---3.1 LXQT
alias lxstart="nvim ~/.config/autostart-scripts"
alias lxout="nvim ~/.config/plasma-workspace/shutdown"
#---3.2 OPENBOX
alias cdop="cd ~/.config/openbox"
alias opfd="nvim ~/.config/openbox"
alias opconf="nvim ~/.config/openbox/config"
alias opkey="nvim ~/.config/openbox/keys"
alias opstart="nvim ~/.config/openbox/start"
alias opmd="nvim ~/.config/openbox/README.md"
#---3.3 STUMPWM
alias cdst="cd ~/.config/stumpwm"
alias stfd="nvim ~/.config/stumpwm"
alias stconf="nvim ~/.config/stumpwm/autostart"
alias stvar="nvim ~/.config/stumpwm/vars.sh"
alias ststart="nvim ~/.config/stumpwm/startup.sh"
alias stmd="nvim ~/.config/stumpwm/README.md"
#---3.4 AWESOME
alias cdaw="cd ~/.config/awesome"
alias awfd="nvim ~/.config/awesome"
alias awconf="nvim ~/.config/awesome/config.py"
alias awkey="nvim ~/.config/awesome/keybind.py"
alias awstart="nvim ~/.config/awesome/autostart.sh"
alias awmd="nvim ~/.config/awesome/README.md"
#---3.5 TINT2
alias cdtt="cd ~/.config/tint2"
alias ttfd="nvim ~/.config/tint2"
alias ttmd="nvim ~/.config/tint2/README.md"
