#!/usr/bin/env bash
#  ▄▄▄· ▄▄▄· ▄▄▄  ▄▄▄        ▄▄▄▄▄
# ▐█ ▄█▐█ ▀█ ▀▄ █·▀▄ █·▪     •██
#  ██▀·▄█▀▀█ ▐▀▀▄ ▐▀▀▄  ▄█▀▄  ▐█.▪
# ▐█▪·•▐█ ▪▐▌▐█•█▌▐█•█▌▐█▌.▐▌ ▐█▌·
# .▀    ▀  ▀ .▀  ▀.▀  ▀ ▀█▄▀▪ ▀▀▀
#---- 1.System
# Grub
alias grupdate="sudo grub-mkconfig -o /boot/grub/grub.cfg"

#---- 2.Package manager
#---2.1 SEARCH
# Search in online repositories
alias aptss="aptitude search"
# Search local packages
alias aptssl="aptitude search '~i(~n $name|~d $description)'"
# Search for package info
alias aptinf="aptitude show"
# Search for package files
alias aptfiles="dpkg -L"

#---2.2 INSTALL
# Istall from remote repository
alias aptin="sudo aptitude install"
alias aptinb="sudo apt -t buster-backports install"
# Install from local package
alias aptinl="sudo dpkg -i"
# Download a package
alias aptdw="sudo aptitude install --download-only"

#---2.3 REMOVE
# Remove a package
alias aptrm="sudo aptitude remove"
# Remove completly include dependencies
alias aptrmf="sudo aptitude purge"
# Remove unneeded dependecy
alias aptnd="sudo apt autoremove"
# Remove old downloaded packages
alias aptcl="sudo aptitude autoclean"

#---2.4 UPDATE
# Update repositories database
alias aptu="sudo aptitude update"
alias update="sudo aptitude update"
# Upgrade packages
alias aptug="sudo aptitude upgrade"
alias upgrade="sudo parrot-upgrade; flatpak update"
# List avaible upgrades
alias aptuls="apt list --upgradable -a"
alias upgradels="apt list --upgradable -a"

#---- 3.Configuration files | dotfiles
#---3.1 MATE
alias mtstart="nvim ~/.config/autostart-scripts"
alias mtout="nvim ~/.config/plasma-workspace/shutdown"
#---3.2 BERRY
alias cdbr="cd ~/.config/berry"
alias brfd="nvim ~/.config/berry"
alias brconf="nvim ~/.config/berry/autostart"
alias brstart="nvim ~/.config/berry/startup.sh"
alias brkey="nvim ~/.config/berry/keybind.sh"
alias brmd="nvim ~/.config/berry/README.md"
#---3.3 STUMPWM
alias cdst="cd ~/.stumpwm.d/"
alias stfd="emacs ~/.stumpwm.d/"
alias stconf="emacs ~/.stumpwm.d/init.lisp"
alias ststart="nvim ~/.stumpwm.d/autostart.sh"
alias stkey="emacs ~/.stumpwm.d/keybind.lisp"
alias strd="emacs ~/.stumpwm.d/README.org"
#---3.4 XMonad
alias cdxm="cd ~/.xmonad"
alias xmfd="nvim ~/.xmonad"
alias xmconf="nvim ~/.xmonad/xmonad.hs"
alias xmstart="nvim ~/.xmonad/autostart.sh"
alias xmkey="nvim ~/.xmonad/keybind.hs"
alias xmrd="nvim ~/.xmonad/README.org"
#---3.5 LEMONBAR
alias cdlb="cd ~/.config/lemonbar"
alias lbfd="nvim ~/.config/lemonbar"
alias lbmd="nvim ~/.config/lemonbar/README.md"

#---- 4.Applications
alias vs="codium"
