#!/usr/bin/env bash
#  ▄▄▄· ▄▄▄· ▄▄▄  ▄▄▄        ▄▄▄▄▄
# ▐█ ▄█▐█ ▀█ ▀▄ █·▀▄ █·▪     •██
#  ██▀·▄█▀▀█ ▐▀▀▄ ▐▀▀▄  ▄█▀▄  ▐█.▪
# ▐█▪·•▐█ ▪▐▌▐█•█▌▐█•█▌▐█▌.▐▌ ▐█▌·
# .▀    ▀  ▀ .▀  ▀.▀  ▀ ▀█▄▀▪ ▀▀▀
#---- 1.System
# Grub
alias grupdate="sudo grub-mkconfig -o /boot/grub/grub.cfg"

#---- 2.Package manager
#---2.1 SEARCH
# Search in online repositories
alias aptss="aptitude search"
# Search local packages
alias aptssl="aptitude search '~i(~n $name|~d $description)'"
# Search for package info
alias aptinf="aptitude show"
# Search for package files
alias aptfiles="dpkg -L"

#---2.2 INSTALL
# Istall from remote repository
alias aptin="sudo aptitude install"
alias aptinb="sudo apt -t buster-backports install"
# Install from local package
alias aptinl="sudo dpkg -i"
# Download a package
alias aptdw="sudo aptitude install --download-only"

#---2.3 REMOVE
# Remove a package
alias aptrm="sudo aptitude remove"
# Remove completly include dependencies
alias aptrmf="sudo aptitude purge"
# Remove unneeded dependecy
alias aptnd="sudo apt autoremove"
# Remove old downloaded packages
alias aptcl="sudo aptitude autoclean"

#---2.4 UPDATE
# Update repositories database
alias aptu="sudo aptitude update"
alias update="sudo aptitude update"
# Upgrade packages
alias aptug="sudo aptitude upgrade"
alias upgrade="sudo aptitude upgrade; flatpak update"
# List avaible upgrades
alias aptuls="apt list --upgradable -a"
alias upgradels="apt list --upgradable -a"

#---- 3.Configuration files | dotfiles
#---3.1 MATE
alias mtstart="nvim ~/.config/autostart-scripts"
alias mtout="nvim ~/.config/plasma-workspace/shutdown"
#---3.2 BERRY
alias cdbr="cd ~/.config/berry"
alias brfd="nvim ~/.config/berry"
alias brconf="nvim ~/.config/berry/autostart"
alias brstart="nvim ~/.config/berry/startup.sh"
alias brkey="nvim ~/.config/berry/keybind.sh"
alias brmd="nvim ~/.config/berry/README.md"
#---3.3 BSPWM
alias cdbp="cd ~/.config/bspwm"
alias bpfd="nvim ~/.config/bspwm"
alias bpconf="nvim ~/.config/bspwm/bspwmrc"
alias bpstart="nvim ~/.config/bspwm/autostart.sh"
alias bpkey="nvim ~/.config/bspwm/keybind.sh"
alias bpmd="nvim ~/.config/bspwm/README.md"
#---3.4 SPECTRWM
alias cdsp="cd ~/.config/spectrwm"
alias spfd="nvim ~/.config/spectrwm"
alias spconf="nvim ~/.config/spectrwm/spectrwm.conf"
alias spstart="nvim ~/.config/spectrwm/autostart.conf"
alias spkey="nvim ~/.config/spectrwm/keybind.conf"
alias spmd="nvim ~/.config/spectrwm/README.md"
#---3.5 POLYBAR
alias cdpb="cd ~/.config/polybar"
alias pbfd="nvim ~/.config/polybar"
alias pbmd="nvim ~/.config/polybar/README.md"

#---- 4.Applications
alias vs="codium"
