#!/usr/bin/env bash
# you can use ~/.xprofile to autostart on login

# If it´s not running, Run it
function run {
	if ! pgrep $1 ;
	then
		$@&
	fi
}

# If you want to use XFCE config tools
#run xfce-mcs-manager
#-- Polkit | Pam
run /usr/libexec/polkit-gnome-authentication-agent-1
run /usr/lib64/libexec/kf5/pam_kwallet_init
#-- Compositor
run picom --config $HOME/.config/picom/picom.conf
#-- Notification
run dunst
#-- Status bar
run tint2
#-- Dock
run docky
#-- Widgets
#conky -c $HOME/.config/conky/
#-- Wallpaper
~/.fehbg	#Automatic
#feh --bg-fill '/home/aix/MEGA/Wallpaper/General-Art/66398581_p0.jpg' #Static
#-- Reload Xresources
#xrdb ~/.Xresources


#-- Demons
run redshift
#run greenclip daemon
run tilda
#run urxvtd
#run pcmanfm --daemon-mode
#run megasync

#-- Applications
#run kitty
#run firefox
#run telegram-desktop

#-- Scripts
#run vitas
#run wal -R

# Applets
sleep 1 &&
run qlipper	#Clipboard
sleep 1 &&
run nm-applet	#Network
sleep 1 &&
run pa-applet	#Volume
sleep 1 &&
run lxqt-powermanagement	#Power manager
