#!/usr/bin/env bash
# you can use ~/.xprofile to autostart on login
export QT_QPA_PLATFORMTHEME="qt5ct"

# If it´s not running, Run it
run() { [ $(pgrep $1) ] || $@& }

# If you want to use XFCE config tools
#run xfce-mcs-manager
#-- POLKIT | PAM | KEYRING
run /usr/libexec/polkit-gnome-authentication-agent-1
run /usr/lib64/libexec/kf5/pam_kwallet_init
#-- LOCKSCREEN
#run xscreensaver -nosplash
#run i3lock
#-- COMPOSITOR
#run picom 
#run picom -b --backend glx --vsync
run picom --config ${HOME}/.config/picom/picom.conf
#-- NOTIFICATION
run dunst 
#run dunst -config "${HOME}/.config/dunst/dunstrc.conf"
#-- DOCK
run latte
#run latte --layout
#-- WIDGETS
#conky -c "${HOME}/.config/conky/"
#-- WALLPAPER
#mpv?								# Dynamic
#feh --bg-fill "{$HOME}/MEGA/Wallpaper/General-Art/66398581_p0.jpg" # Static
run pcmanfm --desktop							# Desktop icons

#-- Demons
run redshift
run tilda
#run urxvtd
#run pcmanfm --daemon-mode
#run emacs --daemon

#-- Scripts
#run vitas
#run dual_monitor
#run wal -R

#-- APPLETS
sleep 1 && run qlipper		# Clipboard
sleep 1 && run nm-applet	# Network
sleep 1 && run pa-applet	# Volume
sleep 1 && run lxqt-powermanagement # Power manager
