#!/bin/sh
# PekWM start file
# It gets run on pekwm startup, after the theme and all config has loaded

# -- PolicyKit | Polkit
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

# -- Tray icon - Applets
# power manager
# network applet
# brightness
# volume
# clipboard
# Tray system

# -- Demon Processes
# Notification deamon
#run pcmanfm --daemon-mode
#run urxvtd
#run megasync
#run greenclip daemon
#[ ! -s ~/.config/mpd/pid ] && mpd

# -- Start application on login
#run telegram-desktop
#run firefox
#run konsole
#run tilda

# -- Compositor
compton &

# -- Wallpaper
# Automatic
#~/.fehbg
# Static
feh --bg-fill "$HOME/MEGA/Wallpaper/Animewe/oregai.jpg"

# -- Polybar
Ptheme="adi1"
polybar -c "$HOME/.config/polybar/$Ptheme.ini" main &

# -- Reload xresources
xrdb ~/.Xresources
