#!/bin/bash
#  ________  _______   ________  ________      ___    ___ 
# |\   __  \|\  ___ \ |\   __  \|\   __  \    |\  \  /  /|
# \ \  \|\ /\ \   __/|\ \  \|\  \ \  \|\  \   \ \  \/  / /
#  \ \   __  \ \  \_|/_\ \   _  _\ \   _  _\   \ \    / / 
#   \ \  \|\  \ \  \_|\ \ \  \\  \\ \  \\  \|   \/  /  /  
#    \ \_______\ \_______\ \__\\ _\\ \__\\ _\ __/  / /    
#     \|_______|\|_______|\|__|\|__|\|__|\|__|\___/ /     
#        github.com/yowls                    \|___|/   	

# Load Preferences
bash $HOME/.config/berry/vars.sh

# 1.Load TAGS for workspaces
#source ~/.config/berry/workspace.sh

# 2.Load the RULES for windows
#source ~/.config/berry/rule.sh

# 3.Load the Berry THEME
bash $HOME/.config/berry/Themes/$Btheme.sh

# 4.Load on login STARTUP programs
bash $HOME/.config/berry/startup.sh

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Monospace-9"
