#!/usr/bin/env bash

#  ________  _______   ________  ________      ___    ___ 
# |\   __  \|\  ___ \ |\   __  \|\   __  \    |\  \  /  /|
# \ \  \|\ /\ \   __/|\ \  \|\  \ \  \|\  \   \ \  \/  / /
#  \ \   __  \ \  \_|/_\ \   _  _\ \   _  _\   \ \    / / 
#   \ \  \|\  \ \  \_|\ \ \  \\  \\ \  \\  \|   \/  /  /  
#    \ \_______\ \_______\ \__\\ _\\ \__\\ _\ __/  / /    
#     \|_______|\|_______|\|__|\|__|\|__|\|__|\___/ /     
#            github.com/yowls                \|___|/   	


# Load Preferences
source ".config/berry/vars.sh"

# 1.Load the keybind for manage WINDOWS
#source ".config/berry/window.sh"

# 2.Load the keybind for manage LAYOUTS
#source ".config/berry/layout.sh"

# 3.Load TAGS for workspaces
#source ".config/berry/workspace.sh"

# 4.Load personal KEYBINDS
sxhkd -c .config/berry/sxhkdrc &

# 5.Load the herbstluft THEME
source ".config/berry/Themes/$Btheme.sh"

# 6.Load the RULES for windows
#source ".config/berry/rule.sh"

# 7.Load on login STARTUP programs
source ".config/berry/startup.sh"

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Dina-9"