#!/usr/bin/env bash
# you can use ~/.xprofile to autostart on login

# If it´s not running, Run it
run() { [ $(pgrep $1) ] || $@& }

# If you want to use XFCE config tools
#run xfce-mcs-manager
#-- POLKIT | PAM
run lxqt-policykit-agent
#-- COMPOSITOR
#run picom
#run picom -b --backend glx --vsync
run picom --config ${HOME}/.config/picom/picom.conf
#-- NOTIFICATION
run dunst
#run deadd-notification-center
#-- STATUS BAR
run tint2
#run tint2 -c ${HOME}/.config/tint2/config
#-- APPLETS
run lxqt-powermanagement	# Power manager
run nm-applet			# Network
run pa-applet			# Volume
run qlipper			# Clipboard
#-- DOCK
run docky
#-- WIDGETS
#conky -c "${HOME}/.config/conky/"
#-- WALLPAPER
#script									# Dynamic
#feh --bg-fill '/home/yowls/MEGA/Wallpaper/General-Art/66398581_p0.jpg' # Static
run pcmanfm-qt --desktop						# Desktop icons

#-- Demons
run redshift
run tilda
#run urxvtd
#run pcmanfm-qt --daemon-mode
#run thunar --daemon
#run emacs --daemon

#-- Scripts
#run vitas
#run dual_monitor
#run wal -R
